import  { useState, useEffect } from "react";

import "chart.js/auto";
import ProcessTimeline from "./Components/HorizontalTimeline";
import MainChart from "./Components/lineChart";
import DetailedTable from "./Components/detailedTable";
// import LogData from "./jsonLogs.json";
import axios from "axios";
import ChatbotResult from "./Components/ChatbotResult";
import NavBar from "../navBar";
import { useNavigate } from "react-router-dom";

type Timeline = "1m" | "5m" | "30m" | "1hr" | "4hr" | "1D" |"30D";
type Event = {
  timestamp: string;
  hostname: string;
  process: string;
  message: string;
  update_status: string; // Add this line to match LogEvent type
  [key: string]: any;
};

export default function LogAnalysis() {
  // const [selectedTimeline, setSelectedTimeline] = useState<number | null>(null);
  const [activeTimeline, setActiveTimeline] = useState<Timeline>("5m");
  const [selectedProcess, setSelectedProcess] = useState<string | null>(null);
  const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  // const [isChatOpen, setChatOpen] = useState(false);
  // const [initialMessage, setInitialMessage] = useState<string | null>(null);
  const [aiResponse, setAiResponse] = useState<string | null>(null);
  const [showChatbotResult, setShowChatbotResult] = useState(false);

  const timelines: Timeline[] = ["1m", "5m", "30m", "1hr", "4hr", "1D" , '30D'];
 const navigate = useNavigate()
  const fetchEvents = async () => {
    try {
      const response = await fetch(
        "http://10.2.0.26:5006/invoke_anomulus_error",
        {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
          // body: JSON.stringify({
          //   data: {
          //     message: "message", // Include the message you want to send
          //   },
          // }),
        }
      );
      const data = await response.json()
      if (!response.ok) {
        throw new Error("Network response was not ok");
      }
      // const data = LogData
      console.log("response : ", data);

      setEvents(data.status);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchEvents();
  }, []); // You might want to include activeTimeline or other dependencies here

  const handleRowClick = (process: string) => {
    setSelectedProcess(process);
  };

  const handleAskAI = async (event: Event) => {
    console.log('event : ' , event);
    
    try {
      const response = await axios.post("http://10.2.0.26:5009/anomaly_logs", {
        message: event.message,
      });

      // const response = {
      //   "data": "{\"response\":[\"**1). Error Context**\\na). **What system or component generated this\",\" log entry?**\\n   - The log entry was generated by an unspecified system or component. The \\\"logger\\\" field is left empty.\\n\\nb). **\",\"What was the user's action or request at the time of this error?**\\n   - The log entry does not provide any information about the user's action or request.\\n\\nc). **Are there any related log entries that might provide more context or details about this error?**\\n   - The log\",\" data does not contain any related log entries.\\n\\n**2). Error Analysis**\\na). **What is the exact meaning of the \\\"user token not found\\\" error?**\\n   - The \\\"user token not found\\\" error indicates that the system cannot find or authenticate the user's token. This could be due to several reasons, such as an invalid token, an expired token, or the user not being authenticated in the first place.\\n\\nb). **Are there any specific conditions or criteria that trigger this error?**\\n   - This error is most likely triggered when the system attempts to perform an operation that requires user authentication\",\" and fails to find or validate the user's token.\\n\\nc). **How frequently does this error occur based on the log data?**\\n   - The log data does not provide information on the frequency of this error.\\n\\n**3). Issue Identification**\\na). **What might be causing the user token to be missing in this scenario?**\\n   - There could be several reasons why the user token is missing, such as:\\n     - The user's token has expired and has not been refreshed.\\n     - The user's token has been revoked or deleted.\\n     - The system is unable to validate the user's token due to configuration issues or security vulnerabilities.\\n\\nb). **Are there any security vulnerabilities or configuration issues that could lead to this error?**\\n   - Yes, if the system is vulnerable to token forgery or theft, it could allow attackers to access user accounts without proper authentication. Additionally, misconfigurations in authentication or token handling can also lead to this error.\\n\\n**4). Remedies**\\na). **What steps can be taken to prevent or resolve this error in the future?**\\n   - Implement proper token management practices, including regular token expiration and refresh mechanisms.\\n   - Secure user tokens from\",\" unauthorized access and theft.\\n   - Review and rectify any configuration issues related to authentication and token handling.\\n\\nb). **Are there any workarounds or temporary solutions that can be implemented to mitigate the impact of this error?**\\n   - Provide users with clear instructions on how to handle token expiration and refresh.\\n   - Implement a system for users to report or reset their tokens in case of loss or theft.\\n\\n**5). Anomalies**\\na). **Are there any unusual patterns or spikes in the occurrence of this error?**\\n   - The log data does not provide information on any unusual patterns or spikes.\\n\\nb). **Does the error correlate with specific user actions, system events, or time periods?**\\n   - The log data does not provide information on any correlations.\"]}\n",
      //   "message": "Log received",
      //   "status": "success"
      // }
      // console.log("CLICKED");

      console.log('response : ' , response);
      

      const data = JSON.parse(response.data.data);

      console.log('data : ' , data);


      
      const botMessage = data.response.join("\n");

      // Set the raw response
      setAiResponse(botMessage);
      setShowChatbotResult(true);
    } catch (error) {
      console.error("Error calling the AI:", error);
    }
  };

  // Filter events based on selected process
  const filteredEvents = selectedProcess
    ? events.filter((event) => event.process === selectedProcess)
    : events;

  if (loading) return <div>Loading...</div>;
  if (error) return <div>Error: {error}</div>;

  return (
    <div className="w-[screen] h-[100vh] flex flex-col">
      <NavBar />
      <div className="flex w-screen h-screen overflow-y-scroll cursor-default">
        <div className="w-full h-[235vh] flex justify-center items-center bg-[#f2f7f8]">
          <div className="flex flex-col w-[90vw] h-[215vh] bg-[#ffffff] rounded-[1rem] gap-y-[2vh] mb-[5vh]">
            <div className="text-[#006e74] text-[1.3rem] flex w-[100%] h-[5vh] mt-[2vh] ml-[5vh] justify-start">
              Log Analysis
            </div>
            <div className="flex gap-[2vh] h-[4vh] w-auto mr-[5vh]">
                <button 
                  className="bg-[#006e74] text-[0.95rem] text-white h-[4vh] w-[8vw] rounded-md shadow-md hover:bg-[#005d63] transition-all"
                  onClick={() => navigate('/LogOverview')}
                >
                 Log Overview
                </button>
                <button 
                  className="bg-[#006e74] text-[0.95rem] text-white h-[4vh] w-[8vw] rounded-md shadow-md hover:bg-[#005d63] transition-all"
                  onClick={() => navigate('/LogCluster')}
                >
                  Clusters
                </button>
              </div>
            <div className="flex flex-col justify-between items-center w-[100%] gap-y-[3vh]">
              <div className="TimelineChanger flex w-[100%] h-[5vh] justify-end items-center">
                <div className="TimeLineChangerInside flex w-[25vw] h-[5vh] mr-[15vh] items-center justify-end bg-[#F2F7F8] rounded-[1vh] cursor-default">
                  {timelines.map((timeline) => (
                    <div
                      key={timeline}
                      className={`flex w-[20%] h-[100%] justify-center items-center cursor-pointer ${
                        activeTimeline === timeline
                          ? "text-[#0097ac] bg-[#D7E0E3] rounded-[1vh]"
                          : ""
                      }`}
                      onClick={() => setActiveTimeline(timeline)}
                    >
                      {timeline}
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div className="flex flex-col h-[160vh] gap-[5vh]">
              <div className="flex justify-center items-center flex-grow">
                <div className="w-[85%] max-w-full bg-[#F2F7F8] rounded-[1rem] p-[2rem]">
                  <MainChart
                    events={filteredEvents}
                    activeTimeline={activeTimeline}
                  />
                  <div className="mt-8 overflow-x-auto">
                    <DetailedTable
                      events={events}
                      onRowClick={handleRowClick}
                      onAskAI={handleAskAI}
                    />
                  </div>
                </div>
              </div>

              <div className="flex justify-center items-center flex-grow mt-[5px]">
                <div className="w-[85%] max-w-full bg-[#F2F7F8] rounded-[1rem] p-[2rem] flex flex-col items-center justify-center">
                  <div className="text-[#006e74] text-[1.5rem] font-semibold mb-4">
                    Process Timeline
                  </div>
                  <ProcessTimeline events={filteredEvents} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {showChatbotResult && aiResponse && (
        <ChatbotResult
          message={aiResponse}
          onClose={() => setShowChatbotResult(false)}
        />
      )}
    </div>
  );
}
